### PR TITLE
Update ARO dnsmasq configuration to match current ARO operator - 4.12

### PR DESCRIPTION
**Pull request by tsatam**
# NOTE - When merging, please squash this PR and include the `CARRY:` prefix in the commit message. 

### Which issue this PR addresses:

- Fixes [ARO-4098](https://issues.redhat.com/browse/ARO-4098)
  - (sub-task of [ARO-4065](https://issues.redhat.com/browse/ARO-4065))
- Fixes [ARO-3474](https://issues.redhat.com/browse/ARO-3474)

This PR is a combination and replacement of the following PRs:
- https://github.com/jewzaam/installer-aro/pull/21
- https://github.com/jewzaam/installer-aro/pull/23

### What this PR does / why we need it:

Brings in the latest ARO DNSMasq configuration from the ARO Operator into the installer, to be put down at install time. The two notable changes are:
- Fix resolv.conf changes during Azure host servicing events 
- Removes ignitionv2 types from installer-aro and use ignitionv3 types to replace them. 

### Test plan for issue:

Unit tests for machineconfigs have been updated to expect the new definitions, all unit tests pass. 

Created an ARO-Installer image by revendoring the installer-aro dependency within ARO-Installer to the HEAD of this branch, and successfully performed cluster installation, and validated that the `99-{master,worker}-aro-dns` MachineConfigs were created with Ignition version 3.2. This has been done with the 4.11 and 4.10 branches as well. 

### Is there any documentation that needs to be updated for this PR?
N/A

### Additional notes
This change will need to be carried to all release branches. PRs are open:
- 4.11: https://github.com/jewzaam/installer-aro/pull/25
- 4.10: https://github.com/jewzaam/installer-aro/pull/26

### CODE REVIEW

**Review by s-fairchild — APPROVED** [review]
LGTM! Thanks for swapping out the string literal constants for constant types.

**Comment by tsatam** [comment]
Tested this change in a fresh cluster install, in tandem with the operator change against a cluster, and confirmed that the operator reconciliation diff is trivial (just a metadata change to set OwnerReference to the MachineConfigPool:

```
INFO[2023-09-06T11:35:33-04:00]pkg/util/dynamichelper/dynamichelper.go:152 dynamichelper.(*dynamicHelper).ensureOne.func1() Update MachineConfig.machineconfiguration.openshift.io/99-worker-aro-dns:   &v1.MachineConfig{                                                                                                                                                                                                                                                                                                                            
        TypeMeta: {},                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        ObjectMeta: v1.ObjectMeta{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                ... // 10 identical fields                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                Labels:          {"machineconfiguration.openshift.io/role": "worker"},                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                Annotations:     nil,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
-               OwnerReferences: nil,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
+               OwnerReferences: []v1.OwnerReference{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
+                       {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
+                               APIVersion:         "machineconfiguration.openshift.io/v1",                                                                                                                                                                                                                                                                                                                                                                                                                                                           
+                               Kind:               "MachineConfigPool",                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
+                               Name:               "worker",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
+                               UID:                "3cacc5ae-a804-48ac-98a7-9cba73f4d501",                                                                                                                                                                                                                                                                                                                                                                                                                                                           
+                               Controller:         &true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
+                               BlockOwnerDeletion: &true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
+                       },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
+               },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                Finalizers:                nil,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                ZZZ_DeprecatedClusterName: "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                ManagedFields:             {{Manager: "cluster-bootstrap", Operation: "Update", APIVersion: "machineconfiguration.openshift.io/v1", Time: s"2023-09-06 09:19:02 -0400 EDT", ...}},                                                                                                                                                                                                                                                                                                                                                    
        },
        Spec: {Config: {Raw: `{"ignition":{"config":{"replace":{"verification":{}}},"proxy":{}`...}},
  } 
INFO[2023-09-06T11:35:34-04:00]pkg/util/dynamichelper/dynamichelper.go:152 dynamichelper.(*dynamicHelper).ensureOne.func1() Update MachineConfig.machineconfiguration.openshift.io/99-master-aro-dns:   &v1.MachineConfig{
        TypeMeta: {},
        ObjectMeta: v1.ObjectMeta{
                ... // 10 identical fields
                Labels:          {"machineconfiguration.openshift.io/role": "master"},
                Annotations:     nil,
-               OwnerReferences: nil,
+               OwnerReferences: []v1.OwnerReference{
+                       {
+                               APIVersion:         "machineconfiguration.openshift.io/v1",
+                               Kind:               "MachineConfigPool",
+                               Name:               "master",
+                               UID:                "13c267b8-27a8-49f5-b433-ca4ef908680f",
+                               Controller:         &true,
+                               BlockOwnerDeletion: &true,
+                       },
+               },
                Finalizers:                nil,
                ZZZ_DeprecatedClusterName: "",
                ManagedFields:             {{Manager: "cluster-bootstrap", Operation: "Update", APIVersion: "machineconfiguration.openshift.io/v1", Time: s"2023-09-06 09:19:01 -0400 EDT", ...}},
        },
        Spec: {Config: {Raw: `{"ignition":{"config":{"replace":{"verification":{}}},"proxy":{}`...}},
  }
```

This results in a no-op change which does not cause new rendered MachineConfigs or node reboots.

**Review by SudoBrendan — APPROVED** [review]
Love love love the refactor for gotmpl! LGTM

**Comment by lranjbar** [comment]
LGTM! Thanks for doing all the testing on this @tsatam

**Pull request merged**
