### PR TITLE
Rebase ARO carry patches on the release-4.10 branch

### PR DESCRIPTION
**Pull request by darthhexx**
Rebases the existing carry patches on the upstream release 4.10 branch with one notable change in the patches that needs to be taken note of. The `AzureMachineProviderSpec` definition has moved to the openshift/api and therefore the machinesets specs are defined under a different API Group. There are also related changes required in the ARO-RP as a result of this change.

Reference commit: https://github.com/openshift/installer/commit/f9725ddd9496b999ac06bd0343791d7c50b00d48

### CODE REVIEW

**Review by mbarnes — COMMENTED** [review]
I verified every individual commit still builds but didn't have time to look at the changes in detail or compare it to the 4.9 patch set.  I'll try to do that tomorrow.

**Review by mbarnes — CHANGES_REQUESTED** [review]
Compared to 4.9 patch set and the commits are nearly identical.

LGTM but with one small request: please move "[CI: switch test container to golang 1.17](https://github.com/jewzaam/installer-aro/pull/12/commits/4d0d06c76a8921d87d8e33d4ba388e97198bc984)" to be the first commit instead of last.  This way we can make sure each subsequent commit not only builds but also passes `hack/go-test.sh`.

Would also be good to offer that patch upstream, if only for the `release-4.10` branch.  I'm surprised it released with `hack/go-tests.sh` broken.

**Comment by mbarnes** [comment]
> please move "[CI: switch test container to golang 1.17](https://github.com/jewzaam/installer-aro/pull/12/commits/4d0d06c76a8921d87d8e33d4ba388e97198bc984)" to be the first commit instead of last.  This way we can make sure each subsequent commit not only builds but also passes `hack/go-test.sh`.

Update: I did this myself locally and verified each commit passes `hack/go-test.sh`.

**Comment by darthhexx** [comment]
Good call @mbarnes. I moved the Golang 1.17 CI commit to be the first.

**Comment by darthhexx** [comment]
Now that we have Go 1.17 CI support fro the ARO-RP and https://github.com/Azure/ARO-RP/pull/2070 has passed its tests, this PR is ready for review.

**Review by ross-bryan — APPROVED** [review]
lgtm

**Pull request merged**
