### PR TITLE
Fix resolv.conf changes during Azure host servicing events

### PR DESCRIPTION
**Pull request by s-fairchild**
### Which issue this PR addresses:

Fixes

https://issues.redhat.com/browse/ARO-3474

### What this PR does / why we need it:

If the network interfaces are brought up/down without restarting NetworkManager, our resolv.conf will be overwritten by NetworkManager. This can occur during [Azure Host Servicing](https://learn.microsoft.com/en-us/azure/developer/intro/hosting-apps-on-azure) events.

See [NetworkManager-dispatcher](https://networkmanager.dev/docs/api/latest/NetworkManager-dispatcher.html) documentation for more information, such as available actions.

I have created a machineconfig locally containing the changes and applied them to both master and worker nodes successfully.

Update dnsmasq controller to have a use a second operator flag. This is to control the application of the dnsmasq reboot script, and prevent unscheduled worker node changes.

### CODE REVIEW

**Review by petrkotas — APPROVED** [review]
LGTM, the same as https://github.com/Azure/ARO-RP/pull/2995. We will need to align to have it only once.

**Comment by s-fairchild** [comment]
@petrkotas Thanks for the review, [pushed small changes the same as here](https://github.com/Azure/ARO-RP/pull/2995#issuecomment-1613123813)

**Review by cadenmarchese — APPROVED** [review]

**Review by cadenmarchese — CHANGES_REQUESTED** [review]
Before merge, let's update this script with the changes in https://github.com/Azure/ARO-RP/pull/2995/files, and get PRs in for release-4,10 and release-4.12 as well.

**Review by cadenmarchese — CHANGES_REQUESTED** [review]
As discussed, we are going to go with https://github.com/Azure/ARO-RP/pull/3140/files and associated installer-aro PRs instead, which include this, so we can close this PR.

**Pull request closed without merging**
